### ISSUE TITLE
DON'T DOWNLOAD

### ISSUE THREAD

**Issue by Ashvir16** [amgxv/SpotifyAdBlocker-macOS#14]
I use m1 Mac and spotify beta, worked, I closed it, opened the next day and access point 19 wont let me log in to any sort of account or make any. Tried to delete, nothing. Deleted all spotify related files & spotify, restart, then redownload and still broken. 

I have to use the intel version of spotify now (luckily I guess could've been worse). For the m1 optimized version though I'm pretty fucked until they release another version which may not happen for months. This can break spotify on mac.

**Comment by MrGKanev** [comment]
@Ashvir16  open your etc/hosts file and remove everything under localhost. (In terminal "sudo nano /etc/hosts") OR

Easy Uninstaller
Run this at the Terminal: sh <(curl -Ss https://raw.githubusercontent.com/amgxv/SpotifyAdBlocker-macOS/master/silent-uninstall.sh)

Or clone the repo and run : ./uninstaller.sh
